### ISSUE TITLE
Add a concourse health CLI that can be used in K8s to check whether the db is healthy or not

### ISSUE THREAD

**Issue by jtnelson** [cinchapi/concourse#552]
concourse status isn't enough because the db can still be running but not in a healthy state (e.g., GC out of memory, etc)

`concourse health` should return things like
- Health: RUNNING_OK | STOPPED | RUNNING_FAILED
- Memory usage?
- Cache usage?

**Comment by jtnelson** [comment]
Can do something like this in k8s

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: concourse
  labels:
    app: concourse
spec:
  serviceName: concourse
  replicas: 1
  selector:
    matchLabels:
      app: concourse
  template:
    metadata:
      labels:
        app: concourse
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: concourse-pool
      containers:
      - name: concourse
        image: docker.io/cinchapi/concourse:0.11.7
        ports:
          - containerPort: 1717
          - containerPort: 9010
        envFrom:
          - configMapRef:
              name: concourse-config
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
          limits:
            cpu: "6"
            memory: "24Gi"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "concourse status | grep -q 'running'"
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "concourse status | grep -q 'running'"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/data
  volumeClaimTemplates:
  // ... existing code ...
```
